---
- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
      region: us-east-1
      instance_type: t2.nano
      ami: ami-0c02fb55956c7d316
      hostname: vikas6
  tasks:
    - name: Create an ec2 instance
      tags: "ec2"
      ec2:
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         instance_tags:
           server: "{{ hostname }}"
           Name: "{{ hostname }}"
         wait: true
         region: "{{ region }}"
         aws_access_key: AKIAUVWMXFC3P64SF6EG
         aws_secret_key: 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
         vpc_subnet_id: subnet-00f58c876e9fada13
         exact_count: 1         
         count_tag: 
           server: "{{ hostname }}"
         assign_public_ip: yes
      register: ec2
