---
- name: Create a new Demo EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
      region: us-east-1
      instance_type: t2.nano
      ami: ami-0c02fb55956c7d316
      hostname: vikas
  tasks:
    - name: Create an ec2 instance
      tags: "ec2"
      ec2:
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         instance_tags:
           server: "{{ hostname }}"
         wait: true
         name: "{{ hostname }}"
         region: "{{ region }}"
         aws_access_key: AKIA45DDQJO2FD45DCED
         aws_secret_key: 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
         vpc_subnet_id: subnet-05dc34715673e090a
         exact_count: 1         
         count_tag: 
           server: "{{ hostname }}"
         assign_public_ip: yes
      register: ec2
